[project]
name = "astrosight"
version = "0.1"
authors = [
  { name="Austin Lucas Lake", email="austinlake04@gmail.com" },
]
description = "Image processing library for astrophotography"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache License 2.0",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy",
    "opencv",
	"pyqt3",
    "rawpy",
	"treelib",
	"tqdm"
]

[project.urls]
Homepage = "https://github.com/austinlucaslake/astrosight"

[project.optional-dependencies]
dev = ["black", "autopep8", "flake8", "flake8-docstrings", "autoflake", "pytest", "pipreqs", "pip-tools"]

[project.scripts]
astrosight-cli = "astrosight.cli:main"
